# Generated by Django 3.1.2 on 2021-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='bill_number',
            field=models.CharField(max_length=100),
        ),
    ]
